version: '3.8'

services:
  databese:
    image: postgres:15.7
    container_name: test-container
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=luna
      - POSTGRES_PASSWORD=202011418
      - POSTGRES_DB=resapi 
    volumes:
      - ./postgres:/var/lib/postgresql/data
